name: flutter_string_encryption
description: Cross-platform string encryption using common best-practices.
version: 0.2.0
author: Stefano Rodriguez <hlsroddy@gmail.com>
homepage: https://github.com/sroddy/flutter_string_encryption

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=1.24.0 <3.0.0'

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.github.sroddy.flutterstringencryption
    pluginClass: FlutterStringEncryptionPlugin
